### ISSUE TITLE
[Question] How verbose does the test runner need to be?

### ISSUE THREAD

**Issue by msomji** [exercism/java-test-runner#1]
Would just parsing what get printed out by running gradle test suffice our needs or are we thinking that it would be better to implement something intercept each test? (https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/TestListener.html).

**Comment by sshine** [comment]
To answer this question, we should probably regard [the test-runner interface](https://github.com/exercism/automated-tests/blob/master/docs/interface.md).

The executable script that a test-runner provides [outputs](https://github.com/exercism/automated-tests/blob/master/docs/interface.md#output-format) a JSON object, so whether this is made with a shell script that parses `gradle test` output (in which case some use of [`jq`](https://github.com/stedolan/jq) would be useful), or an extension using `TestListener`, both appear viable until we explore further.

I don't know the output format of `gradle test`, but if there is any ambiguity in parsing this, e.g. if naming a test case in a specific way may interfere with parsing the outcome of running a test, then this would be an argument against shell scripting, since we'd have to overcome an unnecessary serialize-deserialize step.

I also don't know how extending the test suite with `TestListener` actually works. But since a test-runner should probably be able to deal with uploaded files that don't compile, the executable script that a test-runner provides should at least handle that `gradle test` never actually tests and instead exits with a non-zero exit code. The C# test-runner [handles this](https://github.com/exercism/csharp-test-runner/blob/master/src/Exercism.TestRunner.CSharp/TestRunner.cs) with its `ProjectCompiler`. We could handle this in a shell script to begin with and expand on a pure-Java solution later.

Since you have initiated building a Java test-runner, I think you should go in either way you feel like and report back once you've concluded that one approach is favorable or unfavorable in some way. We can, after all, change our minds.

**Comment by msomji** [comment]
I have been exploring how to implement this using gradle interceptors, which seems to be pretty promising. I am able to build a json object of tests passing/failing and am also able to capture any logging the student would have while trying to implement the solution. The last missing piece is capturing a helpful stacktrace when there are task level errors i.e compilation errors and such.  [Here is a link if you are interested](https://github.com/msomji/java-test-runner/tree/gradle-spike-1). Feedback is welcomed just keep in mind that this might not be the final implementation either.
