### ISSUE TITLE
Nucleotide Count did not detect exception thrown for invalid nucleotide

### ISSUE THREAD

**Issue by bobahop** [exercism/java-test-runner#45]
When I run this student's code locally it correctly throws an exception for inputting "AGXXACT". But the online tester yesterday said nothing was thrown. Perhaps it has something to do with it being a record, since my class solution passed all tests a few minutes ago?

```
import java.util.HashMap;
import java.util.Map;

record NucleotideCounter(String valor) {

    public Map<Character, Integer> nucleotideCounts() {

        HashMap<Character, Integer> devolver = new HashMap<>();
        devolver.put('A', 0);
        devolver.put('C', 0);
        devolver.put('G', 0);
        devolver.put('T', 0);
        if (valor.isEmpty()) return devolver;
      /*  if (valor.matches("A")) {
            throw new IllegalArgumentException(" Error ");
        }*/
        for (int i = 0; i < valor.length(); i++) {
            Character letra = valor.charAt(i);
            if (letra=='X') throw new IllegalArgumentException(" Error ");
            Integer numero = devolver.get(letra);
            devolver.put(letra, (numero + 1));
        }
        return devolver;
    }
}
```
![info](https://user-images.githubusercontent.com/32035397/150422099-59e2ef1e-7a3a-4fb9-affc-c83055fadb4d.JPG)

**Comment by ericbalawejder** [comment]
I am able to reproduce the behavior from the test-runner on my local machine. The last test is different in that it never calls `nucleotideCounts()`. It is looking for the constructor to validate the input and not the method `nucleotideCounts()`. In the example you provided, the exception won't be thrown because the validation is in the method and not the constructor. Is it possible that you had an outdated version of the tests and the test-runner had the more current tests?

**Comment by bobahop** [comment]
It was so long ago and I've since ripped out all of the JavaScript stuff from my machine.

**Comment by ericbalawejder** [comment]
No worries. Just trying to clean up old issues.
